// +build ignore

// TEMPORARY AUTOGENERATED FILE: easyjson bootstapping code to launch
// the actual generator.

package main

import (
  "fmt"
  "os"

  "dynexpr/codegen"
)

func main() {
  g := codegen.NewGenerator()
  g.SetPkg("data", "dynexpr/codegen/test/data")
  if err := g.Run(os.Stdout); err != nil {
    fmt.Fprintln(os.Stderr, err)
    os.Exit(1)
  }
}
