// +build ignore

// TEMPORARY AUTOGENERATED FILE: easyjson bootstapping code to launch
// the actual generator.

package main

import (
  "fmt"
  "os"

  "dynexpr/codegen"

  pkg "dynexpr/codegen/test/data"
)

func main() {
  g := codegen.NewGenerator()
  g.SetPkg("data", "dynexpr/codegen/test/data")
  g.Add(pkg.BankAccount{})
  g.Add(pkg.BankDetails{})
  g.Add(pkg.Child{})
  g.Add(pkg.FamilyDetail{})
  g.Add(pkg.Person{})
  if err := g.Run(os.Stdout); err != nil {
    fmt.Fprintln(os.Stderr, err)
    os.Exit(1)
  }
}
