// +build ignore

// TEMPORARY AUTOGENERATED FILE: easyjson bootstapping code to launch
// the actual generator.

package main

import (
  "fmt"
  "os"

  "github.com/mailru/easyjson/gen"

  pkg "dynexpr/codegen/test/data"
)

func main() {
  g := gen.NewGenerator("person_easyjson.go")
  g.SetPkg("data", "dynexpr/codegen/test/data")
  g.Add(pkg.EasyJSON_exporter_BankAccount(nil))
  g.Add(pkg.EasyJSON_exporter_BankDetails(nil))
  g.Add(pkg.EasyJSON_exporter_Child(nil))
  g.Add(pkg.EasyJSON_exporter_FamilyDetail(nil))
  g.Add(pkg.EasyJSON_exporter_Person(nil))
  if err := g.Run(os.Stdout); err != nil {
    fmt.Fprintln(os.Stderr, err)
    os.Exit(1)
  }
}
