// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  data

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( BankAccount ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* BankAccount ) UnmarshalJSON([]byte) error { return nil }
func ( BankAccount ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* BankAccount ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BankAccount *BankAccount

func ( BankDetails ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* BankDetails ) UnmarshalJSON([]byte) error { return nil }
func ( BankDetails ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* BankDetails ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BankDetails *BankDetails

func ( Child ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Child ) UnmarshalJSON([]byte) error { return nil }
func ( Child ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Child ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Child *Child

func ( FamilyDetail ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* FamilyDetail ) UnmarshalJSON([]byte) error { return nil }
func ( FamilyDetail ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* FamilyDetail ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_FamilyDetail *FamilyDetail

func ( Person ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Person ) UnmarshalJSON([]byte) error { return nil }
func ( Person ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Person ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Person *Person
